// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg4WEUWGd6GC5pn0nl4vyRzJ9Tdpnk8B0',
    appId: '1:791784054069:android:f0a87cbb161aed8d2f407c',
    messagingSenderId: '791784054069',
    projectId: 'classroom-2ba8b',
    databaseURL: 'https://classroom-2ba8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'classroom-2ba8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzmdCFqrfHnTBGGxzDZ6Cy4-xOpMU-tXk',
    appId: '1:791784054069:ios:71959c794425c6ac2f407c',
    messagingSenderId: '791784054069',
    projectId: 'classroom-2ba8b',
    databaseURL: 'https://classroom-2ba8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'classroom-2ba8b.appspot.com',
    androidClientId: '791784054069-dcqg619qt2gtv141ga12uhsgf15p43b9.apps.googleusercontent.com',
    iosClientId: '791784054069-als655sb6q1hu2r906muqvslipqsg77a.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleclassroomClone',
  );
}
